[package]
name = "ilp"
version = "0.3.0"
authors = ["Evan Schwartz <evan@ripple.com>"]
description = "Interledger client library"
license = "Apache-2.0"

[dependencies]
base64 = "0.9.3"
byteorder = "1.2.6"
bytes = "0.4.10"
chrono = "0.4.6"
env_logger = "0.5.13"
futures = "0.1.24"
hex = "0.3.2"
hyper = "0.12.11"
lazy_static = "1.1.0"
log = "0.4.5"
num-bigint = "0.2.0"
num-traits = "0.2.6"
quick-error = "1.2.2"
reqwest = "0.9.2"
ring = "0.13.2"
serde = "1.0.79"
serde_derive = "1.0.79"
serde_json = "1.0.31"
tokio = "0.1.11"
tokio-io = "0.1.9"
tokio-tungstenite = { git = "https://github.com/emschwartz/tokio-tungstenite" }
tokio-tcp = "0.1.2"
tungstenite = { git = "https://github.com/emschwartz/tungstenite-rs" }
url = "1.7.1"
webpki = "0.18.1"

[dependencies.rustls]
version = "0.13.1"
features = ["dangerous_configuration"]