[package]
name = "interledger"
version = "0.4.0"
authors = ["Evan Schwartz <evan@ripple.com>"]
description = "Interledger client library"
license = "Apache-2.0"
edition = "2018"

[lib]
name = "interledger"
path = "src/lib.rs"

[main]
name = "interledger"
path = "src/main.rs"

[dependencies]
base64 = "0.10.1"
ring = "0.14.6"
bytes = "0.4.12"
clap = "2.32.0"
env_logger = "0.6.1"
futures = "0.1.25"
hyper = "0.12.25"
interledger-btp = { path = "../interledger-btp", version = "0.1.0" }
interledger-http = { path = "../interledger-http", version = "0.2.0" }
interledger-ildcp = { path = "../interledger-ildcp", version = "0.2.0" }
interledger-packet = { path = "../interledger-packet", version = "0.1.0" }
interledger-router = { path = "../interledger-router", version = "0.1.0" }
interledger-service = { path = "../interledger-service", version = "0.2.0" }
interledger-service-util = { path = "../interledger-service-util", version = "0.1.0" }
interledger-spsp = { path = "../interledger-spsp", version = "0.1.0" }
interledger-stream = { path = "../interledger-stream", version = "0.1.0" }
interledger-store-memory = { path = "../interledger-store-memory", version = "0.2.0" }
parking_lot = "0.7.1"
tokio = "0.1.16"
url = "1.7.2"

[badges]
circle-ci = { repository = "emschwartz/interledger-rs" }
codecov = { repository = "emschwartz/interledger-rs" }
