[package]
name = "interledger"
version = "0.4.0"
authors = ["Evan Schwartz <evan@ripple.com>"]
description = "Interledger client library"
license = "Apache-2.0"
edition = "2018"
repository = "https://github.com/emschwartz/interledger-rs"

[lib]
name = "interledger"
path = "src/lib.rs"

[features]
default = ["cli"]
cli = [
    "btp",
    "ccp",
    "http",
    "store-memory",
    "ildcp",
    "spsp",
    "interledger-router",
    "interledger-service-util",
    "interledger-store-redis",
    "interledger-api",
]
btp = ["interledger-btp"]
ccp = ["interledger-ccp"]
http = ["interledger-http"]
store-memory = ["interledger-store-memory"]
ildcp = ["interledger-ildcp"]
spsp = ["interledger-spsp", "stream"]
stream = ["interledger-stream", "ildcp"]

[dependencies]
base64 = "0.10.1"
bytes = "0.4.12"
clap = "2.32.0"
env_logger = "0.6.1"
futures = "0.1.25"
hex = "0.3.2"
hyper = "0.12.25"
interledger-api = { path = "../interledger-api", version = "0.1.0", optional = true }
interledger-btp = { path = "../interledger-btp", version = "0.2.1", optional = true }
interledger-ccp = { path = "../interledger-ccp", version = "0.1.0", optional = true }
interledger-http = { path = "../interledger-http", version = "0.2.1", optional = true }
interledger-ildcp = { path = "../interledger-ildcp", version = "0.2.1", optional = true }
interledger-packet = { path = "../interledger-packet", version = "0.2.1" }
interledger-router = { path = "../interledger-router", version = "0.2.1", optional = true }
interledger-service = { path = "../interledger-service", version = "0.2.1" }
interledger-service-util = { path = "../interledger-service-util", version = "0.2.1", optional = true }
interledger-spsp = { path = "../interledger-spsp", version = "0.2.1", optional = true }
interledger-stream = { path = "../interledger-stream", version = "0.2.1", optional = true }
interledger-store-memory = { path = "../interledger-store-memory", version = "0.2.1", optional = true }
interledger-store-redis = { path = "../interledger-store-redis", version = "0.2.1", optional = true}
log = "0.4.6"
parking_lot = "0.7.1"
ring = "0.14.6"
serde = "1.0.89"
tokio = "0.1.16"
tower-web = "0.3.6"
url = "1.7.2"

[dev-dependencies]
net2 = "0.2.33"
rand = "0.6.5"
redis = "0.10.0"
reqwest = "0.9.16"
serde_json = "1.0.39"

[badges]
circle-ci = { repository = "emschwartz/interledger-rs" }
codecov = { repository = "emschwartz/interledger-rs" }
