version: 2
jobs:
  build:
    docker:
      - image: circleci/rust
        environment:
          CARGO_HOME: /home/circleci/.cargo
    steps:
      - checkout
      - restore_cache:
          keys:
            - project-v2-{{ checksum "Cargo.toml" }}
            - project-v2-
      - run:
          name: Install Cargo Make
          command: cargo install --debug cargo-make || true
      - run:
          name: Audit Dependencies
          command: cargo make --no-workspace audit
      - run:
          name: Run Cargo Make Workspace Flow
          command: cargo make --no-workspace workspace-ci-flow
      - save_cache:
          key: project-v2-{{ checksum "Cargo.toml" }}
          paths:
            - ./target
            - /home/circleci/.cargo
