version: 2
jobs:
  build:
    docker:
      - image: circleci/rust
        environment:
          CARGO_HOME: /home/circleci/.cargo
    steps:
      - checkout
      - restore_cache:
          keys:
            - project-v2-{{ checksum "Cargo.toml" }}
            - project-v2-
      - run:
          name: Install Cargo Extensions
          command: cargo install --quiet cargo-kcov cargo-audit && rustup component add rustfmt
      - run:
          name: Install kcov
          command: >-
            sudo apt-get install cmake g++ pkg-config jq libcurl4-openssl-dev libelf-dev libdw-dev binutils-dev libiberty-dev
            && cargo kcov --print-install-kcov-sh | sh
      - run:
          name: Install Redis (for end-to-end test)
          command: sudo apt-get install redis-server
      - run:
          name: Build
          command: RUSTFLAGS="-C link-dead-code" cargo build --tests --all-features
      - run:
          name: Test
          command: cargo test --all --all-features
      - run:
          name: Check Formatting
          command: cargo fmt --all -- --check
      - run:
          name: Audit Dependencies
          command: cargo audit
      - run:
          name: Generate Coverage Report
          command: cargo kcov --all --no-clean-rebuild
      - run:
          name: Upload Code Coverage
          command: "bash <(curl -s https://codecov.io/bash)"
      - save_cache:
          key: project-v2-{{ checksum "Cargo.toml" }}
          paths:
            - ./target
            - /home/circleci/.cargo
